export interface CodeAnalysisFormData {
  errorType: string
  errorMessage: string
  codeSnippet: string
  language: string
  framework: string
  additionalContext: string
}

export type AnalysisStep = 1 | 2 | 3

const ERROR_DESCRIPTIONS: Record<string, string> = {
  "Syntax Error":         "a SyntaxError — the code violates the grammatical rules of the language and cannot be parsed",
  "Runtime Error":        "a RuntimeError — the code is syntactically valid but fails during execution",
  "Type Error":           "a TypeError — an operation is applied to a value of an incompatible type",
  "Logic Error":          "a LogicError — the code runs without exceptions but produces incorrect results",
  "Build Error":          "a BuildError — the project fails to compile or bundle",
  "Network / API Error":  "a Network/API Error — a failure in an HTTP request or external service call",
  "Reference Error":      "a ReferenceError — an identifier is used before it is declared or outside its scope",
  "Null / Undefined Error":"a Null/Undefined Error — code attempts to access a property on a null or undefined value",
  "Other":                "an error that requires investigation",
}

export function compileAnalysisPrompt(data: CodeAnalysisFormData): string {
  const s: string[] = []

  const lang     = data.language.trim()     || "the language in use"
  const fw       = data.framework.trim()    || null
  const ctx      = data.additionalContext.trim() || null
  const errType  = data.errorType           || "Error"
  const errDesc  = ERROR_DESCRIPTIONS[errType] ?? "an error"
  const hasCode  = !!data.codeSnippet.trim()
  const hasError = !!data.errorMessage.trim()
  const langSlug = data.language.toLowerCase().replace(/[^a-z0-9#+]/g, "")

  // ── Header ──────────────────────────────────────────────────────
  s.push(`# AI Debugging Prompt — ${errType}`)
  s.push(`> Generated by PromptCraft AI`)
  s.push(`> Copy this prompt into ChatGPT, Claude, Gemini, Cursor, or Copilot to receive a structured solution.`)
  s.push(``)
  s.push(`---`)
  s.push(``)

  // ── 1. Error Summary ────────────────────────────────────────────
  s.push(`## 1. Error Summary`)
  s.push(``)
  s.push(`I am encountering ${errDesc}.`)
  if (hasError) {
    s.push(``)
    s.push(`**Full error message / stack trace:**`)
    s.push(``)
    s.push("```")
    s.push(data.errorMessage.trim())
    s.push("```")
  }
  s.push(``)

  // ── 2. Error Location ───────────────────────────────────────────
  s.push(`## 2. Error Location`)
  s.push(``)
  if (hasCode) {
    s.push(`**Problematic code that triggers this error:**`)
    s.push(``)
    s.push(`\`\`\`${langSlug}`)
    s.push(data.codeSnippet.trim())
    s.push("```")
  } else {
    s.push(`No code snippet has been provided. Based on the error message and stack trace above, please help identify the most likely originating file, function, line number, or code pattern.`)
  }
  s.push(``)

  // ── 3. Root Cause Analysis ──────────────────────────────────────
  s.push(`## 3. Root Cause Analysis`)
  s.push(``)
  s.push(`Please perform a thorough root cause analysis and address each of the following:`)
  s.push(``)
  s.push(`- **Primary cause:** What specific condition directly triggers this error?`)
  s.push(`- **Contributing factors:** What surrounding conditions make this error possible (wrong types, missing null checks, incorrect state, timing issues)?`)
  s.push(`- **Trigger scenario:** Does this error occur always, intermittently, or only under specific conditions or environments?`)
  if (fw) {
    s.push(`- **Framework-specific behaviour:** Are there ${fw}-specific lifecycle rules, conventions, or known pitfalls that contribute to this error?`)
  }
  s.push(`- **Dependency issues:** Could a version mismatch, breaking API change, or library incompatibility be involved?`)
  s.push(``)

  // ── 4. Conceptual Analogy ────────────────────────────────────────
  s.push(`## 4. Conceptual Analogy`)
  s.push(``)
  s.push(`Provide a clear, memorable real-world analogy that explains **why this class of error occurs** — not just what it is. The analogy should:`)
  s.push(``)
  s.push(`- Map the underlying programming concept to a familiar everyday situation`)
  s.push(`- Help build lasting mental intuition so this error can be recognised and avoided in the future`)
  s.push(`- Be concise (2–4 sentences)`)
  s.push(``)

  // ── 5. Technical Context ─────────────────────────────────────────
  s.push(`## 5. Technical Context`)
  s.push(``)
  s.push(`- **Language:** ${lang}`)
  s.push(`- **Framework / Library:** ${fw ?? "Not specified"}`)
  if (ctx) {
    s.push(`- **Additional context:** ${ctx}`)
  }
  s.push(``)
  s.push(`Take this context into account when diagnosing the error. If the language or framework has known quirks or common pitfalls related to this error type, please highlight them explicitly.`)
  s.push(``)

  // ── 6. Investigation Steps ───────────────────────────────────────
  s.push(`## 6. Investigation Steps`)
  s.push(``)
  s.push(`Walk through the following checklist before proposing a fix:`)
  s.push(``)
  s.push(`1. Confirm the error is reproducible and isolate the minimum code that triggers it.`)
  s.push(`2. Examine the full call stack to trace execution from the entry point to the failure site.`)
  s.push(`3. Inspect the runtime values of key variables at the point of failure.`)
  s.push(`4. Determine whether the error is environment-specific (development vs. production, client vs. server, OS, runtime version).`)
  if (fw) {
    s.push(`5. Review ${fw} configuration, plugin settings, or middleware that may influence the behaviour.`)
    s.push(`6. Check changelogs of recently upgraded dependencies for breaking changes.`)
  } else {
    s.push(`5. Review recent configuration changes, environment variable updates, or dependency upgrades.`)
  }
  s.push(``)

  // ── 7. Resolution Request ────────────────────────────────────────
  s.push(`## 7. Resolution Request`)
  s.push(``)
  s.push(`You are an expert ${lang} developer${fw ? ` with deep knowledge of ${fw}` : ""}. Based on everything above:`)
  s.push(``)
  s.push(`1. **Identify** the precise root cause.`)
  s.push(`2. **Fix** — provide the corrected code with inline comments explaining each key change and why it resolves the issue.`)
  s.push(`3. **Explain** — in plain language, describe why the original code failed and why the fix works.`)
  s.push(`4. **Alternatives** — if multiple solutions exist, list them in order of preference with trade-offs for each.`)
  s.push(`5. **Prevention** — recommend patterns, lint rules, or architectural decisions that prevent this error class from recurring.`)
  s.push(``)

  // ── 8. Expected Output Format ────────────────────────────────────
  s.push(`## 8. Expected Output Format`)
  s.push(``)
  s.push(`Structure your response using these sections:`)
  s.push(``)
  s.push(`- **Root Cause** — one concise paragraph`)
  s.push(`- **Analogy** — 2–4 sentences mapping the error to an everyday concept`)
  s.push(`- **Corrected Code** — full corrected snippet with inline comments`)
  s.push(`- **Explanation** — why the original failed and why the fix works`)
  s.push(`- **Alternative Solutions** — ranked by preference with trade-off notes`)
  s.push(`- **Prevention Tips** — patterns, tooling, or practices to avoid this error class`)
  s.push(`- **Confidence** — rate your diagnosis (High / Medium / Low) and briefly explain why`)

  return s.join("\n")
}
